### ISSUE TITLE
[Inflearn] Spring Roadmap Complete 🔥

### ISSUE THREAD

**Issue by taek2222** [taek2222/Inflearn_Spring#1]
⛳️ 실천 로드맵 : https://www.inflearn.com/roadmaps/373

**총 9개 코스**

<details>
<summary> 1️⃣ [스프링 입문 - 코드로 배우는 스프링 부트, 웹 MVC, DB 접근 기술] 🔥 진행 중 </summary>

  - [ ] 섹션 0. 강의 소개
  - [ ] 섹션 1. 프로젝트 환경설정
  - [ ] 섹션 2. 스프링 웹 개발 기초
  - [ ] 섹션 3. 회원 관리 예제 - 백엔드 개발
  - [ ] 섹션 4. 스프링 빈과 의존관계
  - [ ] 섹션 5. 회원 관리 예제 - 웹 MVC 개발
  - [ ] 섹션 6. 스프링 DB 접근 기술
  - [ ] 섹션 7. AOP
  - [ ] 섹션 8. 다음으로
</details>

<details>
<summary> 2️⃣ [스프링 핵심 원리 - 기본편] </summary>

  - [ ] 섹션 0. 강의 소개
  - [ ] 섹션 1. 객체 지향 설계와 스프링
  - [ ] 섹션 2. 스프링 핵심 원리 이해1 - 예제 만들기
  - [ ] 섹션 3. 스프링 핵심 원리 이해2 - 객체 지향 원리 적용
  - [ ] 섹션 4. 스프링 컨테이너와 스프링 빈
  - [ ] 섹션 5. 싱글톤 컨테이너
  - [ ] 섹션 6. 컴포넌트 스캔
  - [ ] 섹션 7. 의존관계 자동 주입
  - [ ] 섹션 8. 빈 생명주기 콜백
  - [ ] 섹션 9. 빈 스코프
  - [ ] 섹션 10. 다음으로
</details>

<details>
<summary> 3️⃣ [모든 개발자를 위한 HTTP 웹 기본 지식] </summary>

  - [ ] 섹션 0. 강의 소개
  - [ ] 섹션 1. 인터넷 네트워크
  - [ ] 섹션 2. URI와 웹 브라우저 요청 흐름
  - [ ] 섹션 3. HTTP 기본
  - [ ] 섹션 4. HTTP 메서드
  - [ ] 섹션 5. HTTP 메서드 활용
  - [ ] 섹션 6. HTTP 상태코드
  - [ ] 섹션 7. HTTP 헤더1 - 일반 헤더
  - [ ] 섹션 8. HTTP 헤더2 - 캐시와 조건부 요청
  - [ ] 섹션 9. 다음으로
</details>

<details>
<summary> 4️⃣ [스프링 MVC 1편 - 백엔드 웹 개발 핵심 기술] </summary>

  - [ ] 섹션 0. 강의 소개
  - [ ] 섹션 1. 웹 애플리케이션 이해
  - [ ] 섹션 2. 서블릿
  - [ ] 섹션 3. 서블릿, JSP, MVC 패턴
  - [ ] 섹션 4. MVC 프레임워크 만들기
  - [ ] 섹션 5. 스프링 MVC - 구조 이해
  - [ ] 섹션 6. 스프링 MVC - 기본 기능
  - [ ] 섹션 7. 스프링 MVC - 웹 페이지 만들기
  - [ ] 섹션 8. 다음으로
</details>

<details>
<summary> 5️⃣ [스프링 MVC 2편 - 백엔드 웹 개발 활용 기술] </summary>

  - [ ] 섹션 0. 강의 소개
  - [ ] 섹션 1. 타임리프 - 기본 기능
  - [ ] 섹션 2. 타임리프 - 스프링 통합과 폼
  - [ ] 섹션 3. 메시지, 국제화
  - [ ] 섹션 4. 검증1 - Validation
  - [ ] 섹션 5. 검증2 - Bean Validation
  - [ ] 섹션 6. 로그인 처리1 - 쿠키, 세션
  - [ ] 섹션 7. 로그인 처리2 - 필터, 인터셉터
  - [ ] 섹션 8. 예외 처리와 오류 페이지
  - [ ] 섹션 9. API 예외 처리
  - [ ] 섹션 10. 스프링 타입 컨버터
  - [ ] 섹션 11. 파일 업로드
  - [ ] 섹션 12. 다음으로
</details>

<details>
<summary> 6️⃣ [스프링 DB 1편 - 데이터 접근 핵심 원리] </summary>

  - [ ] 섹션 0. 강의 소개
  - [ ] 섹션 1. JDBC 이해
  - [ ] 섹션 2. 커넥션풀과 데이터소스 이해
  - [ ] 섹션 3. 트랜잭션 이해
  - [ ] 섹션 4. 스프링과 문제 해결 - 트랜잭션
  - [ ] 섹션 5. 자바 예외 이해
  - [ ] 섹션 6. 스프링과 문제 해결 - 예외 처리, 반복
  - [ ] 섹션 7. 다음으로
</details>

<details>
<summary> 7️⃣ [스프링 DB 2편 - 데이터 접근 활용 기술] </summary>

  - [ ] 섹션 0. 강의 소개
  - [ ] 섹션 1. 데이터 접근 기술 - 시작
  - [ ] 섹션 2. 데이터 접근 기술 - 스프링 JdbcTemplate
  - [ ] 섹션 3. 데이터 접근 기술 - 테스트
  - [ ] 섹션 4. 데이터 접근 기술 - MyBatis
  - [ ] 섹션 5. 데이터 접근 기술 - JPA
  - [ ] 섹션 6. 데이터 접근 기술 - 스프링 데이터 JPA
  - [ ] 섹션 7. 데이터 접근 기술 - Querydsl
  - [ ] 섹션 8. 데이터 접근 기술 - 활용 방안
  - [ ] 섹션 9. 스프링 트랜잭션 이해
  - [ ] 섹션 10. 스프링 트랜잭션 전파1 - 기본
  - [ ] 섹션 11. 스프링 트랜잭션 전파2 - 활용
  - [ ] 섹션 12. 다음으로
</details>

<details>
<summary> 8️⃣ [스프링 핵심 원리 - 고급편] </summary>

  - [ ] 섹션 0. 강의 소개
  - [ ] 섹션 1. 예제 만들기
  - [ ] 섹션 2. 쓰레드 로컬 - ThreadLocal
  - [ ] 섹션 3. 템플릿 메서드 패턴과 콜백 패턴
  - [ ] 섹션 4. 프록시 패턴과 데코레이터 패턴
  - [ ] 섹션 5. 동적 프록시 기술
  - [ ] 섹션 6. 스프링이 지원하는 프록시
  - [ ] 섹션 7. 빈 후처리기
  - [ ] 섹션 8. @Aspect AOP
  - [ ] 섹션 9. 스프링 AOP 개념
  - [ ] 섹션 10. 스프링 AOP 구현
  - [ ] 섹션 11. 스프링 AOP - 포인트컷
  - [ ] 섹션 12. 스프링 AOP - 실전 예제
  - [ ] 섹션 13. 스프링 AOP - 실무 주의사항
  - [ ] 섹션 14. 다음으로
</details>

<details>
<summary> 9️⃣ [스프링 부트 - 핵심 원리와 활용] </summary>

  - [ ] 섹션 0. 오리엔테이션
  - [ ] 섹션 1. 스프링 부트 소개
  - [ ] 섹션 2. 웹 서버와 서블릿 컨테이너
  - [ ] 섹션 3. 스프링 부트와 내장 톰캣
  - [ ] 섹션 4. 스프링 부트 스타터와 라이브러리 관리
  - [ ] 섹션 5. 자동 구성(Auto Configuration)
  - [ ] 섹션 6. 외부설정과 프로필1
  - [ ] 섹션 7. 외부설정과 프로필2
  - [ ] 섹션 8. 액츄에이터
  - [ ] 섹션 9. 마이크로미터, 프로메테우스, 그라파나
  - [ ] 섹션 10. 모니터링 메트릭 활용
  - [ ] 섹션 11. 다음으로
</details>
